#!/bin/bash
# This script compiles python source to binaries for the raspberry pi clients

echo "-----------------------------------------------------------------"
echo "     beginning compilation, please grab a cup of coffee"
echo "-----------------------------------------------------------------
"
mkdir -p lib build_tmp >/dev/null
rm -r ./lib/* build_tmp/* >/dev/null

if python3 compile.py build_ext --build-lib ./lib/ --build-temp ./build_tmp
   then
      echo "-----------------------------------------------------------------"
      echo "        FINISHED compiling, copying static files"
      rm -r build_tmp
      rm ./*.c
      mv lib/*.so ./
      rm -r lib
    else
      echo "-----------------------------------------------------------------"
      echo "    compilation FAILED, please reconsider your life choices"
    
fi
echo "--------------------------  DONE  -------------------------------
"
